### PR TITLE
Fix build with SWIG 4.4

### LINKED ISSUE #1979: modpython compiling error with swig 4.4.0
SiD`` on IRC reported this. I can confirm it happens in cygwin.

```
-- Found SWIG: /usr/bin/swig.exe (found suitable version "4.4.0", minimum required is "4.0.1")
```

```
[ 27%] Built target modpython_functions
[ 27%] Building CXX object modules/CMakeFiles/module_modpython.dir/modpython.cpp.o
In file included from /home/user/znc-swig-4.4/modules/modpython.cpp:372:
/home/user/znc-swig-4.4/modules/modpython/pyfunctions.cpp: In function ‘int {anonymous}::ZNC_SWIG_AsCharPtrAndSize(PyObject*, char**, size_t*, int*)’:
/home/user/znc-swig-4.4/modules/modpython/pyfunctions.cpp:149:57: error: ‘SWIG_Python_str_AsChar’ was not declared in this scope; did you mean ‘SWIG_Python_str_FromChar’?
  149 |                                                 *cptr = SWIG_Python_str_AsChar(obj);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~
      |                                                         SWIG_Python_str_FromChar
make[2]: *** [modules/CMakeFiles/module_modpython.dir/build.make:76: modules/CMakeFiles/module_modpython.dir/modpython.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1557: modules/CMakeFiles/module_modpython.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### PR DESCRIPTION
**Pull request by DimStar77**
SWIG 4.4 has dropped the usage of SWIG_NULLPTR again, which means we can't
rely on its presence to identify SWIG >= 4.2.0

Generate a swig_version.h which parses the output of `swig -version` and
writes this in a hex representation, then compare on this

Fixes #1979

### CODE REVIEW

File: modules/modpython/codegen.pl [hunk 1]
```diff
@@ -60,11 +62,10 @@
 		return info;
 	}
 
-// SWIG 4.2.0 replaced SWIG_Python_str_AsChar with SWIG_PyUnicode_AsUTF8AndSize.
-// SWIG doesn't provide any good way to detect SWIG version (other than parsing
-// `swig -version`), but it also introduced SWIG_NULLPTR in 4.2.0.
-// So let's abuse that define to do different code for new SWIG.
-#ifdef SWIG_NULLPTR
+// SWIG_VERSION is defined as 0x040200 for 4.2.0.
+// We use this to detect modern SWIG versions and avoid the "abuse" of
```
Comment (DarthGandalf) [inline modules/modpython/codegen.pl]: SWIG_NULLPTR no longer exists in this code, doesn't need to be mentioned even

**Comment by DarthGandalf** [comment]
Thanks, applied it to 1.10 branch
